version: '3.8'
services:
  mysql:
    image:  mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - my-network

  metabase:
    image: metabase/metabase:v0.48.8
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

